### ISSUE TITLE
azure login picks up wrong tenant

### ISSUE THREAD

**Issue by nbarlowATI** [informatics-lab/aml-jupyterhub#22]
I'm currently still unable to launch even with the `no_auth_spawn_on_aml` config, due to conflicting Azure organisations/tenants.

I get the device login page, go to https://microsoft.com/devicelogin, and enter the code.  I then get the message "Event Login complete" from the spawner, so this seems to work OK.

However, then I get another login page opening on a different tab, along with the following message on the terminal:
```
Performing interactive authentication. Please follow the instructions on the terminal.
WARNING:azureml._vendor.azure_cli_core._profile:Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
```
This doesn't seem to be a "device" login - I don't enter any code, just choose my account. 

Then it stops, because apparently this last login is logging me in to the Turing tenant (although it gives me no choice):
```
Spawn failed: UserErrorException: Message: You are currently logged-in to 4395f4a7-e455-4f95-8a9f-1fbaef6384f9 tenant. You don't have access to 1fedcbc3-e156-45f5-a034-c89c2fc0ac61 subscription, please check if it is in this tenant.
```

Piero also reported initially 2 logins, but for him the second one was no longer necessary when logged in via the Azure CLI on the terminal, and using `az account set` to choose the right subscription.  However, this isn't the case for me - I am logged into the Met Office Informatics Lab tenant on the Azure CLI, and in the portal I have my "Default Directory" set to the Met Office Informatics Lab one, but I still get two login prompts, and the second one seems determined to log me in to the Turing's tenant.

**Comment by nbarlowATI** [comment]
The second login is triggered by the line checking whether the workspace already exists.   
I can reproduce just by doing
```
python
>>> import os
>>> from azureml.core import Workspace
>>> workspace = Workspace(os.environ["SUBSCRIPTION_ID"], os.environ["RESOURCE_GROUP"], os.environ["SPAWN_TO_WORK_SPACE"])
```

**Comment by nbarlowATI** [comment]
This looks helpful: 
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/manage-azureml-service/authentication-in-azureml/authentication-in-azureml.ipynb

If nothing else, can create an InteractiveLoginAuthentication using the correct tenant_id and pass this to the Workspace constructor:
```
from azureml.core.authentication import InteractiveLoginAuthentication
interactive_auth = InteractiveLoginAuthentication(tenant_id="my-tenant-id")
workspace = Workspace(..., auth=interactive_auth)
```

**Comment by tam203** [comment]
Something else to try. Changing `$HOME` - so the `az login` updates the setting in `~/.azure/...` so something I'm thinking of trying is for each users that logging in to write to a different `$HOME` not the `$HOME` of the process running JHub
