### ISSUE TITLE
Allow users to select workspace / VM size

### ISSUE THREAD

**Issue by nbarlowATI** [informatics-lab/aml-jupyterhub#30]
After the user logs in via Azure AD, would be good to offer them a choice of which Workspace to use (or if they want to create a new one).
Can also offer a list of VM sizes for them to choose from.

One thing to consider is that while it is not too difficult for the Service Principal to get a list of all Workspaces in the Resource Group, it is not quite so simple to filter this list to only the ones that the user has access to.

 - [x] Create form where the user can choose from list of workspaces in the Resource Group.
 - [ ] Filter this list to only show workspaces that the User can access.
 - [x] Add ability for user to create a new workspace
 - [x] Add choice of VM size.

**Comment by pierocor** [comment]
The option to create a new workspace has been added to the form page. When selecting this option the redirection to the progress page could take minutes and, in most cases, an error appears:
```
ngrok gateway error
The server returned an invalid or incomplete HTTP response.
```
However, the logs show that both the WS and the CI are created successfully. The user has to manually go to $HOST/hub to be redirected to the CI.

**Comment by tam203** [comment]
Hi @pierocor - I was very impressed with your demo on this last week. My suggestions to streamline the process from a 'scientist who doesn't know or care about Azure' point of view would be:

**Comment by nbarlowATI** [comment]
Closing, as outstanding part of this Issue is specified in more detail in #40
